before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libxml2-dev
language: ruby
rvm:
  - "2.2.3"
services:
  - postgresql
before_script:
  - psql -c 'create database bill_tracker_test;' -U postgres
test:
  adapter: postgresql
  database: bill_tracker_test
  username: postgres
